// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhobqsjwblcjoayfshxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlob2Jxc2p3Ymxjam9heWZzaHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDgwMDksImV4cCI6MjA3MDA4NDAwOX0.0OHrYQ6YVau-roLVW1iL8TrYijOJGqx8ievJCW4bUKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});